# Configurator for the engine buildchain and workflows

name: LewEngine

version: 1.0.0

description: |
  ''

engine:
  build:
    - container: 'true'
    - dir: '.build/'
    - target: 'linux'
    - mode: 'full'
      components:
        - test: 'true'
    - cmd: 'bin/build-engine'

setup:
  linux:
    - env-variables: 'env/linux-variables.env'
    - cmd: 'bin/linux-setup'
  mingw64:
    - env-variables: 'env/mingw64-variables.env'
    - cmd: 'bin/mingw64-setup'

test:

exe:

install: 'false'

clean:
  paths:

